[theme]
base = "dark"
primaryColor = "#ff4b4b"  # สีหลัก (ปุ่ม/Highlight) ปรับได้ตามชอบ
backgroundColor = "#0e1117" # สีพื้นหลัง
secondaryBackgroundColor = "#262730" # สีพื้นหลัง Sidebar/Card
textColor = "#fafafa" # สีตัวหนังสือ